# Generated by Django 4.1.6 on 2023-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=10)),
                ('quality', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='downloads')),
            ],
        ),
    ]
